### PR TITLE
fix mock method $args parameter type

### LINKED ISSUE #1395: PHPStan error with mock method in 1.6.8
### Mockery Version

1.6.8

### PHP Version

PHP 8.3

### Issue Description

phpstan does not detect return value anymore properly

### Steps to Reproduce

```php

class Test
{
    public function test() : string
    {
        return 'Test';
    }
}

$test = \Mockery::mock(Test::class);

$test->shouldReceive('test')->andReturn('Mocked');

echo $test->test();

```

### Expected Behavior

No PHPStan errors

### Actual Behavior

phpstan reports now following error: phpstan: Return type of call to static method Mockery::mock() contains unresolvable type.

### Exception or Error

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by sakarikl**
fix for #1395

### CODE REVIEW

**Comment by sakarikl** [comment]
This still does not fix alias: and such usages, but most normal use cases PHPStan undestands it properly.

and if no parameters given at all also still fails.


But in those cases it might be able to solve with this: https://github.com/phpstan/phpstan-mockery

**Review by ghostwriter — APPROVED** [review]
Looks great, going to merge this pull request.

Thank you.

**Comment by ghostwriter** [comment]
> This still does not fix alias: and such usages

Thank you, made a note to take care of that.

File: library/Mockery.php [hunk 1]
```diff
@@ -468,7 +468,7 @@ public static function isSame($expected): IsSame
      *
      * @template TMock
      *
-     * @param TMock ...$args
+     * @param array<class-string<TMock>|TMock> $args
```
Comment (LastDragon-ru) [inline library/Mockery.php:471]: This is invalid type, because according in the doc you can

```
$mock = \Mockery::mock('MyClass', 'MyInterface', [$constructorArg1, $constructorArg2]);
```

Comment (sakarikl) [reply library/Mockery.php:471]: Yes it is. There are still a lot of different use cases that this does not cover.

**Comment by Harrald** [comment]
While this update fixes a lot of phpstan errors. It also introduces a new one for an edge case in my code:

`Parameter #2 ...$args of static method Mockery::mock() expects class-string<SplFileObject>|SplFileObject, array<int, string> given. `
```
$path = 'php://memory';
$splFileObject = Mockery::mock('SplFileObject', [$path]);
```

It seems that like it only excepts 1 parameter?
These also fail:
`$skuNotFoundException = Mockery::mock('alias:' . SkuDoesNotExistException::class, Exception::class);`
`$supplierModel = Mockery::mock('alias:' . SupplierModel::class, Model::class);`
